### PR TITLE
Added cube root Operator

### PR DESCRIPTION
**Pull request by PeachesMLG**
Closes Issue: https://github.com/Redempt/Crunch/issues/1

Added the cube root operator, I wanted to add an Operator that allows you to root by any power, e.g. root(x, 8) but wasnt sure how to do that with the current codebase

### CODE REVIEW

**Review by Redempt — CHANGES_REQUESTED** [review]
Your PR changes things outside of what it should. It should not change the format of the Operator file (removing indentation on blank lines, changing the other Operators to use method references). Also please follow the format Operators are in, I avoid using method references in the enum values because jitpack doesn't seem to like them.

**Comment by PeachesMLG** [comment]
Yeah, my ide auto formats stuff, ill change that back

**Comment by PeachesMLG** [comment]
welp, I undid the method references, but looks like my ide automatically fixes the indents and I cba to figure out how to turn that off, so :shrug: fix it yourself if u want, idk

**Comment by Redempt** [comment]
Good enough I guess, thanks for the PR

**Pull request merged**
